#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
write_files:
  - path: /tmp/dns_servers_crutch.sh
    content: |    
        DNS_SERVERS="${router_ip}"
        sudo sed -i "s/NETCONFIG_DNS_STATIC_SERVERS=\".*\"/NETCONFIG_DNS_STATIC_SERVERS=\"$DNS_SERVERS\"/" /etc/sysconfig/network/config
        sudo netconfig update -f
#Minion config
  - encoding: b64
    content: ${salt_rancher_conf}
    path: /etc/salt/minion.d/rancher.conf
    permissions: '0644'
    owner: root:root
  - encoding: b64
    content: ${salt_autosign_grains_conf}
    path: /etc/salt/minion.d/autosign-grains.conf
    permissions: '0644'
    owner: root:root
runcmd:
${runcmd}    