#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
  
write_files:
#Salt States
  - encoding: b64
    content: ${salt_top_sls}
    path: /srv/salt/top.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_router_sls}
    path: /srv/salt/router.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_rke_sls}
    path: /srv/salt/rke.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_rancher_sls}
    path: /srv/salt/rancher.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_router_chrony}
    path: /srv/salt/router/ntp.conf
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_router_dhcpd_conf}
    path: /srv/salt/router/dhcpd.conf
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_router_rancher_suse_ru}
    path: /srv/salt/router/stend.local
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_router_addr_arpa}
    path: /srv/salt/router/14.168.192.in-addr.arpa
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_reactor_start}
    path: /srv/reactor/start.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_reactor_delkey}
    path: /srv/reactor/delkey.sls
    permissions: '0644'
    owner: root:salt    
  - encoding: b64
    content: ${salt_main_ntp}
    path: /srv/salt/main/ntp.conf
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_ssh-key_sls}
    path: /srv/salt/ssh-key.sls
    permissions: '0644'
    owner: root:salt
  - path: /srv/salt/registration.sls
    content: |
        registration_sles:
            cmd.run:
              - name: |
                  if [ "$(echo $(SUSEConnect --status-text | grep -A 2 '(SLES/15.3/x86_64)' | tail -1))" = "Not Registered" ]
                    then
                      ping updates.suse.com -c 10
                      ${registration_cmd} > /var/log/registration.log 2>&1
                      zypper ref
                  fi
#Master config
  - encoding: b64
    content: ${salt_master_conf}
    path: /etc/salt/master.d/router.conf
    permissions: '0644'
    owner: root:root
  - encoding: b64
    content: ${salt_autosign_key}
    path: /etc/salt/autosign_grains/autosign_key
    permissions: '0644'
    owner: root:root
#Minion config
  - encoding: b64
    content: ${salt_router_conf}
    path: /etc/salt/minion.d/router.conf
    permissions: '0644'
    owner: root:root
  - encoding: b64
    content: ${salt_autosign_grains_conf}
    path: /etc/salt/minion.d/autosign-grains.conf
    permissions: '0644'
    owner: root:root

runcmd:
${runcmd_router}
